"use client";

import React, { useState, useEffect, useCallback } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import Sidebar from "@/components/Sidebar";
import { dynamicFieldService } from "@/services/dynamicField.service";
import { documentTypeService } from "@/services/documentType.service";
import {
  DynamicField,
  UpdateDynamicFieldPayload,
  FieldType,
  DataSource,
} from "@/types/dynamicField.types";
import { DocumentType } from "@/types/documentType.types";
import {
  ArrowLeft,
  FormInput,
  Edit2,
  Save,
  X,
  CheckCircle2,
  AlertCircle,
  RefreshCw,
  Database,
  FileText,
  Type,
  Hash,
  Calendar,
  DollarSign,
  Mail,
  Phone,
  ToggleLeft,
  ShieldCheck,
  Sparkles,
} from "lucide-react";

const FIELD_TYPE_OPTIONS: { value: FieldType; label: string }[] = [
  { value: "TEXT",     label: "TEXT — Normal text" },
  { value: "NUMBER",   label: "NUMBER — Numeric value" },
  { value: "DATE",     label: "DATE — Date value" },
  { value: "CURRENCY", label: "CURRENCY — Currency/amount" },
  { value: "EMAIL",    label: "EMAIL — Email address" },
  { value: "PHONE",    label: "PHONE — Phone number" },
  { value: "BOOLEAN",  label: "BOOLEAN — Yes/No value" },
];

const DATA_SOURCE_OPTIONS: { value: DataSource; label: string }[] = [
  { value: "EMPLOYEE", label: "EMPLOYEE — From employee data" },
  { value: "COMPANY",  label: "COMPANY — From company data" },
  { value: "PROFILE",  label: "PROFILE — From profile/role" },
  { value: "SYSTEM",   label: "SYSTEM — Generated by system" },
  { value: "MANUAL",   label: "MANUAL — Entered manually" },
];

export default function DynamicFieldDetailClient() {
  const params  = useParams();
  const fieldId = params?.id as string;

  const [collapsed, setCollapsed]           = useState(false);
  const [field, setField]                   = useState<DynamicField | null>(null);
  const [documentTypes, setDocumentTypes]   = useState<DocumentType[]>([]);
  const [loading, setLoading]               = useState<boolean>(true);
  const [error, setError]                   = useState<string | null>(null);

  const [isEditing, setIsEditing]           = useState<boolean>(false);
  const [saving, setSaving]                 = useState<boolean>(false);
  const [editForm, setEditForm]             = useState<UpdateDynamicFieldPayload>({});

  const [toast, setToast] = useState<{ type: "success" | "error"; msg: string } | null>(null);

  const showToast = (type: "success" | "error", msg: string) => {
    setToast({ type, msg });
    setTimeout(() => setToast(null), 4000);
  };

  const populateEditForm = (data: DynamicField) => {
    setEditForm({
      fieldKey:       data.fieldKey  || "",
      fieldName:      data.fieldName || "",
      fieldType:      data.fieldType || "TEXT",
      dataSource:     data.dataSource || "EMPLOYEE",
      documentTypeId: data.documentTypeId ?? null,
      description:    data.description  || "",
      placeholder:    data.placeholder  || "",
      defaultValue:   data.defaultValue || "",
      isRequired:     Boolean(data.isRequired),
      isActive:       data.isActive !== false,
      isSystem:       Boolean(data.isSystem),
      displayOrder:   data.displayOrder || 1,
      remark:         data.remark || "",
    });
  };

  const fetchFieldDetails = useCallback(async () => {
    if (!fieldId) return;
    setLoading(true);
    setError(null);
    try {
      const [fData, docTypeData] = await Promise.all([
        dynamicFieldService.getDynamicFieldById(fieldId),
        documentTypeService.getAllDocumentTypes().catch(() => []),
      ]);
      setField(fData);
      setDocumentTypes(docTypeData);
      populateEditForm(fData);
    } catch (err: any) {
      console.error("Fetch field details error:", err);
      setError(err?.message || "Failed to load dynamic field.");
    } finally {
      setLoading(false);
    }
  }, [fieldId]);

  useEffect(() => { fetchFieldDetails(); }, [fetchFieldDetails]);

  const handleSaveEdits = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!field) return;
    setSaving(true);
    try {
      const payload: UpdateDynamicFieldPayload = {
        ...editForm,
        documentTypeId: editForm.documentTypeId || null,
        displayOrder:   Number(editForm.displayOrder || 1),
      };
      const updated = await dynamicFieldService.updateDynamicField(field.id, payload);
      setField(updated);
      populateEditForm(updated);
      setIsEditing(false);
      showToast("success", `Dynamic field "${updated.fieldName}" updated successfully!`);
    } catch (err: any) {
      console.error("Save field error:", err);
      showToast("error", err?.message || "Failed to update dynamic field.");
    } finally {
      setSaving(false);
    }
  };

  const renderValue = (value: any, placeholder = "—") => {
    if (value === null || value === undefined || value === "") {
      return <span className="text-slate-600 italic">{placeholder}</span>;
    }
    if (typeof value === "boolean") {
      return value ? (
        <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-emerald-950 text-emerald-400 border border-emerald-500/30">Yes</span>
      ) : (
        <span className="px-2 py-0.5 rounded text-[10px] text-slate-500 bg-slate-900 border border-slate-800">No</span>
      );
    }
    if (typeof value === "object") {
      return <pre className="text-xs font-mono text-cyan-300 bg-[#0C101D] p-2 rounded border border-[#1E2638] overflow-x-auto">{JSON.stringify(value, null, 2)}</pre>;
    }
    return <span className="text-slate-100 font-medium">{String(value)}</span>;
  };

  const docTypeObj = documentTypes.find((d) => d.id === field?.documentTypeId);

  return (
    <div className="min-h-screen bg-[#070911] text-slate-100 flex flex-col font-sans selection:bg-indigo-500 selection:text-white">
      <Sidebar collapsed={collapsed} setCollapsed={setCollapsed} />

      <main className={`flex-1 transition-all duration-300 ease-in-out p-4 sm:p-6 lg:p-8 ${collapsed ? "ml-20" : "ml-64"}`}>
        <div className="max-w-5xl mx-auto space-y-6">

          {toast && (
            <div className={`p-4 rounded-xl text-xs font-semibold shadow-2xl flex items-center justify-between border animate-in slide-in-from-top duration-200 ${
              toast.type === "success" ? "bg-emerald-950/90 text-emerald-200 border-emerald-500/40" : "bg-rose-950/90 text-rose-200 border-rose-500/40"
            }`}>
              <div className="flex items-center gap-2">
                {toast.type === "success" ? <CheckCircle2 className="w-4 h-4 text-emerald-400" /> : <AlertCircle className="w-4 h-4 text-rose-400" />}
                <span>{toast.msg}</span>
              </div>
              <button onClick={() => setToast(null)}><X className="w-3.5 h-3.5 opacity-70 hover:opacity-100" /></button>
            </div>
          )}

          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <Link href="/dynamic-field" className="inline-flex items-center gap-2 text-xs font-semibold text-slate-400 hover:text-white transition-colors group">
              <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
              Back to Dynamic Fields
            </Link>

            {field && (
              <div className="flex items-center gap-3">
                <button onClick={fetchFieldDetails} className="p-2.5 rounded-xl bg-[#0F1422] hover:bg-[#151C2F] text-slate-400 hover:text-white border border-[#1E2638] transition-all" title="Refresh">
                  <RefreshCw className={`w-4 h-4 ${loading ? "animate-spin" : ""}`} />
                </button>
                {!isEditing ? (
                  <button onClick={() => setIsEditing(true)} className="gradient-btn flex items-center gap-2 px-5 py-2.5 rounded-xl text-white font-semibold text-xs cursor-pointer shadow-lg shadow-indigo-500/20">
                    <Edit2 className="w-4 h-4" /><span>Edit Field</span>
                  </button>
                ) : (
                  <button onClick={() => { setIsEditing(false); if (field) populateEditForm(field); }} className="px-4 py-2.5 rounded-xl bg-[#141A2C] hover:bg-[#1E2638] text-slate-300 text-xs font-semibold transition-colors">
                    Cancel Editing
                  </button>
                )}
              </div>
            )}
          </div>

          {error && (
            <div className="p-4 rounded-xl bg-rose-950/80 border border-rose-500/40 text-rose-300 text-xs font-medium flex items-center justify-between">
              <div className="flex items-center gap-2"><AlertCircle className="w-4 h-4 text-rose-400" /><span>{error}</span></div>
              <button onClick={fetchFieldDetails} className="px-3 py-1 bg-rose-900 hover:bg-rose-800 rounded text-[11px] text-white font-semibold">Retry</button>
            </div>
          )}

          {loading ? (
            <div className="glass-card p-16 rounded-2xl border border-[#1E2638] text-center space-y-3">
              <RefreshCw className="w-8 h-8 animate-spin mx-auto text-indigo-500" />
              <p className="text-xs font-mono text-slate-400">Loading dynamic field...</p>
            </div>
          ) : field ? (
            <form onSubmit={handleSaveEdits} className="space-y-6">
              <div className="glass-card p-6 rounded-2xl border border-[#1E2638] flex flex-col md:flex-row md:items-center justify-between gap-6">
                <div className="flex items-center gap-4">
                  <div className="w-16 h-16 rounded-2xl bg-gradient-to-tr from-indigo-950 via-slate-900 to-indigo-900 border border-indigo-500/30 flex items-center justify-center text-indigo-400 shadow-xl">
                    <FormInput className="w-8 h-8" />
                  </div>
                  <div>
                    <div className="flex items-center gap-3 flex-wrap">
                      <h1 className="text-2xl font-extrabold text-white">
                        {isEditing ? (
                          <input type="text" required value={editForm.fieldName || ""} onChange={(e) => setEditForm({ ...editForm, fieldName: e.target.value })} className="bg-[#141A2C] border border-[#202B44] rounded-lg px-3 py-1 text-xl text-white font-bold focus:outline-none focus:border-indigo-500 w-auto" />
                        ) : field.fieldName}
                      </h1>
                      <span className="px-3 py-0.5 rounded-full text-xs font-mono font-semibold bg-indigo-950/80 text-indigo-300 border border-indigo-500/30">{field.fieldType}</span>
                      <span className="px-3 py-0.5 rounded-full text-xs font-mono font-semibold bg-slate-900 text-slate-400 border border-slate-700">{field.dataSource}</span>
                    </div>
                  </div>
                </div>
              </div>
            </form>
          ) : (
            <div className="p-12 text-center text-slate-500">Dynamic field record not found.</div>
          )}
        </div>
      </main>
    </div>
  );
}
