"use client";

import React, { useState, useEffect, useCallback } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import Sidebar from "@/components/Sidebar";
import { dynamicFieldService } from "@/services/dynamicField.service";
import { documentTypeService } from "@/services/documentType.service";
import {
  DynamicField,
  UpdateDynamicFieldPayload,
  FieldType,
  DataSource,
} from "@/types/dynamicField.types";
import { DocumentType } from "@/types/documentType.types";
import {
  ArrowLeft,
  FormInput,
  Edit2,
  Save,
  X,
  CheckCircle2,
  AlertCircle,
  RefreshCw,
  Database,
  FileText,
  Type,
  Hash,
  Calendar,
  DollarSign,
  Mail,
  Phone,
  ToggleLeft,
  ShieldCheck,
  Sparkles,
} from "lucide-react";

const FIELD_TYPE_OPTIONS: { value: FieldType; label: string }[] = [
  { value: "TEXT",     label: "TEXT — Normal text" },
  { value: "NUMBER",   label: "NUMBER — Numeric value" },
  { value: "DATE",     label: "DATE — Date value" },
  { value: "CURRENCY", label: "CURRENCY — Currency/amount" },
  { value: "EMAIL",    label: "EMAIL — Email address" },
  { value: "PHONE",    label: "PHONE — Phone number" },
  { value: "BOOLEAN",  label: "BOOLEAN — Yes/No value" },
];

const DATA_SOURCE_OPTIONS: { value: DataSource; label: string }[] = [
  { value: "EMPLOYEE", label: "EMPLOYEE — From employee data" },
  { value: "COMPANY",  label: "COMPANY — From company data" },
  { value: "PROFILE",  label: "PROFILE — From profile/role" },
  { value: "SYSTEM",   label: "SYSTEM — Generated by system" },
  { value: "MANUAL",   label: "MANUAL — Entered manually" },
];

export default function DynamicFieldDetailPage() {
  const params  = useParams();
  const fieldId = params?.id as string;

  const [collapsed, setCollapsed]           = useState(false);
  const [field, setField]                   = useState<DynamicField | null>(null);
  const [documentTypes, setDocumentTypes]   = useState<DocumentType[]>([]);
  const [loading, setLoading]               = useState<boolean>(true);
  const [error, setError]                   = useState<string | null>(null);

  const [isEditing, setIsEditing]           = useState<boolean>(false);
  const [saving, setSaving]                 = useState<boolean>(false);
  const [editForm, setEditForm]             = useState<UpdateDynamicFieldPayload>({});

  const [toast, setToast] = useState<{ type: "success" | "error"; msg: string } | null>(null);

  const showToast = (type: "success" | "error", msg: string) => {
    setToast({ type, msg });
    setTimeout(() => setToast(null), 4000);
  };

  const populateEditForm = (data: DynamicField) => {
    setEditForm({
      fieldKey:       data.fieldKey  || "",
      fieldName:      data.fieldName || "",
      fieldType:      data.fieldType || "TEXT",
      dataSource:     data.dataSource || "EMPLOYEE",
      documentTypeId: data.documentTypeId ?? null,
      description:    data.description  || "",
      placeholder:    data.placeholder  || "",
      defaultValue:   data.defaultValue || "",
      isRequired:     Boolean(data.isRequired),
      isActive:       data.isActive !== false,
      isSystem:       Boolean(data.isSystem),
      displayOrder:   data.displayOrder || 1,
      remark:         data.remark || "",
    });
  };

  const fetchFieldDetails = useCallback(async () => {
    if (!fieldId) return;
    setLoading(true);
    setError(null);
    try {
      const [fData, docTypeData] = await Promise.all([
        dynamicFieldService.getDynamicFieldById(fieldId),
        documentTypeService.getAllDocumentTypes().catch(() => []),
      ]);
      setField(fData);
      setDocumentTypes(docTypeData);
      populateEditForm(fData);
    } catch (err: any) {
      console.error("Fetch field details error:", err);
      setError(err?.message || "Failed to load dynamic field.");
    } finally {
      setLoading(false);
    }
  }, [fieldId]);

  useEffect(() => { fetchFieldDetails(); }, [fetchFieldDetails]);

  const handleSaveEdits = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!field) return;
    setSaving(true);
    try {
      const payload: UpdateDynamicFieldPayload = {
        ...editForm,
        documentTypeId: editForm.documentTypeId || null,
        displayOrder:   Number(editForm.displayOrder || 1),
      };
      const updated = await dynamicFieldService.updateDynamicField(field.id, payload);
      setField(updated);
      populateEditForm(updated);
      setIsEditing(false);
      showToast("success", `Dynamic field "${updated.fieldName}" updated successfully!`);
    } catch (err: any) {
      console.error("Save field error:", err);
      showToast("error", err?.message || "Failed to update dynamic field.");
    } finally {
      setSaving(false);
    }
  };

  const renderValue = (value: any, placeholder = "—") => {
    if (value === null || value === undefined || value === "") {
      return <span className="text-slate-600 italic">{placeholder}</span>;
    }
    if (typeof value === "boolean") {
      return value ? (
        <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-emerald-950 text-emerald-400 border border-emerald-500/30">Yes</span>
      ) : (
        <span className="px-2 py-0.5 rounded text-[10px] text-slate-500 bg-slate-900 border border-slate-800">No</span>
      );
    }
    if (typeof value === "object") {
      return <pre className="text-xs font-mono text-cyan-300 bg-[#0C101D] p-2 rounded border border-[#1E2638] overflow-x-auto">{JSON.stringify(value, null, 2)}</pre>;
    }
    return <span className="text-slate-100 font-medium">{String(value)}</span>;
  };

  const docTypeObj = documentTypes.find((d) => d.id === field?.documentTypeId);

  return (
    <div className="min-h-screen bg-[#070911] text-slate-100 flex flex-col font-sans selection:bg-indigo-500 selection:text-white">
      <Sidebar collapsed={collapsed} setCollapsed={setCollapsed} />

      <main className={`flex-1 transition-all duration-300 ease-in-out p-4 sm:p-6 lg:p-8 ${collapsed ? "ml-20" : "ml-64"}`}>
        <div className="max-w-5xl mx-auto space-y-6">

          {/* Toast */}
          {toast && (
            <div className={`p-4 rounded-xl text-xs font-semibold shadow-2xl flex items-center justify-between border animate-in slide-in-from-top duration-200 ${
              toast.type === "success" ? "bg-emerald-950/90 text-emerald-200 border-emerald-500/40" : "bg-rose-950/90 text-rose-200 border-rose-500/40"
            }`}>
              <div className="flex items-center gap-2">
                {toast.type === "success" ? <CheckCircle2 className="w-4 h-4 text-emerald-400" /> : <AlertCircle className="w-4 h-4 text-rose-400" />}
                <span>{toast.msg}</span>
              </div>
              <button onClick={() => setToast(null)}><X className="w-3.5 h-3.5 opacity-70 hover:opacity-100" /></button>
            </div>
          )}

          {/* Top Bar */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <Link href="/dynamic-field" className="inline-flex items-center gap-2 text-xs font-semibold text-slate-400 hover:text-white transition-colors group">
              <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
              Back to Dynamic Fields
            </Link>

            {field && (
              <div className="flex items-center gap-3">
                <button onClick={fetchFieldDetails} className="p-2.5 rounded-xl bg-[#0F1422] hover:bg-[#151C2F] text-slate-400 hover:text-white border border-[#1E2638] transition-all" title="Refresh">
                  <RefreshCw className={`w-4 h-4 ${loading ? "animate-spin" : ""}`} />
                </button>
                {!isEditing ? (
                  <button onClick={() => setIsEditing(true)} className="gradient-btn flex items-center gap-2 px-5 py-2.5 rounded-xl text-white font-semibold text-xs cursor-pointer shadow-lg shadow-indigo-500/20">
                    <Edit2 className="w-4 h-4" /><span>Edit Field</span>
                  </button>
                ) : (
                  <button onClick={() => { setIsEditing(false); if (field) populateEditForm(field); }} className="px-4 py-2.5 rounded-xl bg-[#141A2C] hover:bg-[#1E2638] text-slate-300 text-xs font-semibold transition-colors">
                    Cancel Editing
                  </button>
                )}
              </div>
            )}
          </div>

          {/* Error */}
          {error && (
            <div className="p-4 rounded-xl bg-rose-950/80 border border-rose-500/40 text-rose-300 text-xs font-medium flex items-center justify-between">
              <div className="flex items-center gap-2"><AlertCircle className="w-4 h-4 text-rose-400" /><span>{error}</span></div>
              <button onClick={fetchFieldDetails} className="px-3 py-1 bg-rose-900 hover:bg-rose-800 rounded text-[11px] text-white font-semibold">Retry</button>
            </div>
          )}

          {/* Loading */}
          {loading ? (
            <div className="glass-card p-16 rounded-2xl border border-[#1E2638] text-center space-y-3">
              <RefreshCw className="w-8 h-8 animate-spin mx-auto text-indigo-500" />
              <p className="text-xs font-mono text-slate-400">Loading dynamic field...</p>
            </div>
          ) : field ? (
            <form onSubmit={handleSaveEdits} className="space-y-6">

              {/* Header Banner */}
              <div className="glass-card p-6 rounded-2xl border border-[#1E2638] flex flex-col md:flex-row md:items-center justify-between gap-6">
                <div className="flex items-center gap-4">
                  <div className="w-16 h-16 rounded-2xl bg-gradient-to-tr from-indigo-950 via-slate-900 to-indigo-900 border border-indigo-500/30 flex items-center justify-center text-indigo-400 shadow-xl">
                    <FormInput className="w-8 h-8" />
                  </div>
                  <div>
                    <div className="flex items-center gap-3 flex-wrap">
                      <h1 className="text-2xl font-extrabold text-white">
                        {isEditing ? (
                          <input type="text" required value={editForm.fieldName || ""} onChange={(e) => setEditForm({ ...editForm, fieldName: e.target.value })} className="bg-[#141A2C] border border-[#202B44] rounded-lg px-3 py-1 text-xl text-white font-bold focus:outline-none focus:border-indigo-500 w-auto" />
                        ) : field.fieldName}
                      </h1>
                      <span className="px-3 py-0.5 rounded-full text-xs font-mono font-semibold bg-indigo-950/80 text-indigo-300 border border-indigo-500/30">{field.fieldType}</span>
                      <span className="px-3 py-0.5 rounded-full text-xs font-mono font-semibold bg-slate-900 text-slate-400 border border-slate-700">{field.dataSource}</span>
                      {field.isActive !== false ? (
                        <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-semibold bg-emerald-950/80 text-emerald-400 border border-emerald-500/30"><CheckCircle2 className="w-3 h-3" />Active</span>
                      ) : (
                        <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-slate-900 text-slate-400 border border-slate-700">Inactive</span>
                      )}
                    </div>
                    <p className="text-xs text-slate-400 font-mono mt-1 flex items-center gap-2">
                      <Sparkles className="w-3 h-3 text-indigo-400" />
                      Template placeholder: <code className="text-indigo-300 font-bold">{`{{${field.fieldKey}}}`}</code>
                    </p>
                  </div>
                </div>

                {isEditing && (
                  <button type="submit" disabled={saving} className="gradient-btn flex items-center gap-2 px-6 py-2.5 rounded-xl text-white font-semibold text-xs cursor-pointer shadow-lg shadow-indigo-500/20 self-end md:self-auto disabled:opacity-40">
                    <Save className="w-4 h-4" /><span>{saving ? "Saving..." : "Save Changes"}</span>
                  </button>
                )}
              </div>

              {/* Details Grid */}
              <div className="glass-card p-6 rounded-2xl border border-[#1E2638] space-y-6">
                <h2 className="text-sm font-bold text-white uppercase tracking-wider font-mono border-b border-[#1E2638] pb-3 flex items-center gap-2">
                  <FormInput className="w-4 h-4 text-indigo-400" />
                  Field Specifications
                </h2>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs">
                  {/* Field Key */}
                  <div className="p-4 bg-[#111626] rounded-xl border border-[#1E2638]">
                    <span className="text-slate-400 block mb-1 font-medium">Field Key (Template Variable)</span>
                    {isEditing ? (
                      <input type="text" required value={editForm.fieldKey || ""} onChange={(e) => setEditForm({ ...editForm, fieldKey: e.target.value.toLowerCase().replace(/[^a-z0-9_]/g, "") })} className="w-full bg-[#141A2C] border border-[#202B44] rounded-lg px-3 py-1.5 text-xs text-white font-mono focus:outline-none focus:border-indigo-500" />
                    ) : (
                      <code className="text-indigo-300 font-mono font-bold">{`{{${field.fieldKey}}}`}</code>
                    )}
                  </div>

                  {/* Field Type */}
                  <div className="p-4 bg-[#111626] rounded-xl border border-[#1E2638]">
                    <span className="text-slate-400 block mb-1 font-medium">Field Type</span>
                    {isEditing ? (
                      <select value={editForm.fieldType || "TEXT"} onChange={(e) => setEditForm({ ...editForm, fieldType: e.target.value as FieldType })} className="w-full bg-[#141A2C] border border-[#202B44] rounded-lg px-2 py-1.5 text-xs text-white focus:outline-none focus:border-indigo-500">
                        {FIELD_TYPE_OPTIONS.map((o) => <option key={o.value} value={o.value} className="bg-[#141A2C]">{o.label}</option>)}
                      </select>
                    ) : renderValue(field.fieldType)}
                  </div>

                  {/* Data Source */}
                  <div className="p-4 bg-[#111626] rounded-xl border border-[#1E2638]">
                    <span className="text-slate-400 block mb-1 font-medium">Data Source</span>
                    {isEditing ? (
                      <select value={editForm.dataSource || "EMPLOYEE"} onChange={(e) => setEditForm({ ...editForm, dataSource: e.target.value as DataSource })} className="w-full bg-[#141A2C] border border-[#202B44] rounded-lg px-2 py-1.5 text-xs text-white focus:outline-none focus:border-indigo-500">
                        {DATA_SOURCE_OPTIONS.map((o) => <option key={o.value} value={o.value} className="bg-[#141A2C]">{o.label}</option>)}
                      </select>
                    ) : (
                      <div className="flex items-center gap-1.5">
                        <Database className="w-3 h-3 text-slate-400" />
                        <span className="text-slate-100 font-medium">{field.dataSource}</span>
                      </div>
                    )}
                  </div>

                  {/* Document Type */}
                  <div className="p-4 bg-[#111626] rounded-xl border border-[#1E2638]">
                    <span className="text-slate-400 block mb-1 font-medium">Document Type</span>
                    {isEditing ? (
                      <select value={editForm.documentTypeId ?? ""} onChange={(e) => setEditForm({ ...editForm, documentTypeId: e.target.value ? Number(e.target.value) : null })} className="w-full bg-[#141A2C] border border-[#202B44] rounded-lg px-2 py-1.5 text-xs text-white focus:outline-none focus:border-indigo-500">
                        <option value="" className="bg-[#141A2C]">All Documents (Global)</option>
                        {documentTypes.map((dt) => <option key={dt.id} value={dt.id} className="bg-[#141A2C]">{dt.documentTypeName} ({dt.documentTypeCode})</option>)}
                      </select>
                    ) : (
                      docTypeObj ? (
                        <div className="flex items-center gap-1.5"><FileText className="w-3 h-3 text-slate-400" /><span className="text-slate-100 font-medium">{docTypeObj.documentTypeName}</span></div>
                      ) : <span className="text-slate-500 italic">All Documents (Global)</span>
                    )}
                  </div>

                  {/* Placeholder */}
                  <div className="p-4 bg-[#111626] rounded-xl border border-[#1E2638]">
                    <span className="text-slate-400 block mb-1 font-medium">Placeholder Text</span>
                    {isEditing ? (
                      <input type="text" value={editForm.placeholder || ""} onChange={(e) => setEditForm({ ...editForm, placeholder: e.target.value })} className="w-full bg-[#141A2C] border border-[#202B44] rounded-lg px-3 py-1.5 text-xs text-white focus:outline-none focus:border-indigo-500" />
                    ) : renderValue(field.placeholder)}
                  </div>

                  {/* Default Value */}
                  <div className="p-4 bg-[#111626] rounded-xl border border-[#1E2638]">
                    <span className="text-slate-400 block mb-1 font-medium">Default Value</span>
                    {isEditing ? (
                      <input type="text" value={editForm.defaultValue || ""} onChange={(e) => setEditForm({ ...editForm, defaultValue: e.target.value })} className="w-full bg-[#141A2C] border border-[#202B44] rounded-lg px-3 py-1.5 text-xs text-white focus:outline-none focus:border-indigo-500" />
                    ) : renderValue(field.defaultValue)}
                  </div>

                  {/* Flags */}
                  <div className="p-4 bg-[#111626] rounded-xl border border-[#1E2638]">
                    <span className="text-slate-400 block mb-2 font-medium">Constraint Flags</span>
                    {isEditing ? (
                      <div className="space-y-2">
                        {[
                          { key: "isRequired", label: "Required" },
                          { key: "isActive",   label: "Active"   },
                          { key: "isSystem",   label: "System Reserved" },
                        ].map(({ key, label }) => (
                          <label key={key} className="flex items-center gap-2 text-xs text-slate-300 cursor-pointer">
                            <input type="checkbox" checked={Boolean((editForm as any)[key])} onChange={(e) => setEditForm({ ...editForm, [key]: e.target.checked })} className="rounded bg-[#141A2C] border-[#202B44] text-indigo-600 focus:ring-0 cursor-pointer" />
                            <span>{label}</span>
                          </label>
                        ))}
                      </div>
                    ) : (
                      <div className="flex flex-wrap gap-2">
                        {field.isRequired && <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-emerald-950 text-emerald-400 border border-emerald-500/30">Required</span>}
                        {field.isActive !== false && <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-cyan-950 text-cyan-400 border border-cyan-500/30">Active</span>}
                        {field.isSystem && <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-amber-950 text-amber-400 border border-amber-500/30">System</span>}
                        {!field.isRequired && !field.isSystem && field.isActive === false && <span className="text-slate-600 italic text-[10px]">No special flags</span>}
                      </div>
                    )}
                  </div>

                  {/* Display Order */}
                  <div className="p-4 bg-[#111626] rounded-xl border border-[#1E2638]">
                    <span className="text-slate-400 block mb-1 font-medium">Display Order</span>
                    {isEditing ? (
                      <input type="number" value={editForm.displayOrder || 1} onChange={(e) => setEditForm({ ...editForm, displayOrder: Number(e.target.value) })} className="w-full bg-[#141A2C] border border-[#202B44] rounded-lg px-3 py-1.5 text-xs text-white font-mono focus:outline-none focus:border-indigo-500" />
                    ) : renderValue(field.displayOrder)}
                  </div>

                  {/* Created At */}
                  <div className="p-4 bg-[#111626] rounded-xl border border-[#1E2638]">
                    <span className="text-slate-400 block mb-1 font-medium">Created</span>
                    {renderValue(field.createdAt ? new Date(field.createdAt).toLocaleString() : null)}
                  </div>

                  {/* Updated At */}
                  <div className="p-4 bg-[#111626] rounded-xl border border-[#1E2638]">
                    <span className="text-slate-400 block mb-1 font-medium">Last Modified</span>
                    {renderValue(field.updatedAt ? new Date(field.updatedAt).toLocaleString() : null)}
                  </div>
                </div>

                {/* Description */}
                <div className="p-4 bg-[#111626] rounded-xl border border-[#1E2638]">
                  <span className="text-slate-400 block mb-1 font-medium text-xs">Description</span>
                  {isEditing ? (
                    <textarea rows={3} value={editForm.description || ""} onChange={(e) => setEditForm({ ...editForm, description: e.target.value })} className="w-full bg-[#141A2C] border border-[#202B44] rounded-lg p-3 text-xs text-white focus:outline-none focus:border-indigo-500" />
                  ) : renderValue(field.description)}
                </div>

                {/* Remark */}
                <div className="p-4 bg-[#111626] rounded-xl border border-[#1E2638]">
                  <span className="text-slate-400 block mb-1 font-medium text-xs">Internal Remark</span>
                  {isEditing ? (
                    <input type="text" value={editForm.remark || ""} onChange={(e) => setEditForm({ ...editForm, remark: e.target.value })} className="w-full bg-[#141A2C] border border-[#202B44] rounded-lg px-3 py-1.5 text-xs text-white focus:outline-none focus:border-indigo-500" />
                  ) : renderValue(field.remark)}
                </div>
              </div>
            </form>
          ) : (
            <div className="p-12 text-center text-slate-500">Dynamic field record not found.</div>
          )}
        </div>
      </main>
    </div>
  );
}
