"use client";

import React, { useState, useEffect, useCallback, useRef } from "react";
import Sidebar from "@/components/Sidebar";
import { dynamicFieldService } from "@/services/dynamicField.service";
import { documentTypeService } from "@/services/documentType.service";
import {
  DynamicField,
  CreateDynamicFieldPayload,
  FieldType,
  DataSource,
  DynamicFieldFilters,
} from "@/types/dynamicField.types";
import { DocumentType } from "@/types/documentType.types";
import {
  FormInput,
  Plus,
  Search,
  Filter,
  RefreshCw,
  Edit2,
  Trash2,
  CheckCircle2,
  AlertCircle,
  X,
  CheckSquare,
  Square,
  ShieldCheck,
  Database,
  Type,
  Hash,
  Calendar,
  DollarSign,
  Mail,
  Phone,
  ToggleLeft,
  FileText,
  Sparkles,
  Copy,
  Check,
  ChevronDown,
} from "lucide-react";

// ─── Constants ────────────────────────────────────────────────────────────────

const FIELD_TYPES: { value: FieldType; label: string; description: string; icon: React.ElementType }[] = [
  { value: "TEXT",     label: "Text",     description: "Normal text value",          icon: Type       },
  { value: "NUMBER",   label: "Number",   description: "Numeric value",              icon: Hash       },
  { value: "DATE",     label: "Date",     description: "Date value",                 icon: Calendar   },
  { value: "CURRENCY", label: "Currency", description: "Currency / amount value",    icon: DollarSign },
  { value: "EMAIL",    label: "Email",    description: "Email address",              icon: Mail       },
  { value: "PHONE",    label: "Phone",    description: "Phone number",               icon: Phone      },
  { value: "BOOLEAN",  label: "Boolean",  description: "Yes / No or true / false",   icon: ToggleLeft },
];

const DATA_SOURCES: { value: DataSource; label: string; description: string; color: string }[] = [
  { value: "EMPLOYEE", label: "Employee", description: "Value comes from employee information.",          color: "text-indigo-400"  },
  { value: "COMPANY",  label: "Company",  description: "Value comes from company information.",           color: "text-cyan-400"    },
  { value: "PROFILE",  label: "Profile",  description: "Value comes from the selected profile/role.",     color: "text-violet-400"  },
  { value: "SYSTEM",   label: "System",   description: "Value is generated by the system.",               color: "text-amber-400"   },
  { value: "MANUAL",   label: "Manual",   description: "Value is entered manually during generation.",    color: "text-rose-400"    },
];

// Auto-suggest a snake_case field key from a human-readable field name
const toFieldKey = (name: string): string =>
  name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s_]/g, "")
    .replace(/\s+/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_|_$/g, "");

const FIELD_TYPE_COLORS: Record<FieldType, string> = {
  TEXT:     "bg-indigo-950/80 text-indigo-300 border-indigo-500/30",
  NUMBER:   "bg-cyan-950/80 text-cyan-300 border-cyan-500/30",
  DATE:     "bg-violet-950/80 text-violet-300 border-violet-500/30",
  CURRENCY: "bg-emerald-950/80 text-emerald-300 border-emerald-500/30",
  EMAIL:    "bg-sky-950/80 text-sky-300 border-sky-500/30",
  PHONE:    "bg-teal-950/80 text-teal-300 border-teal-500/30",
  BOOLEAN:  "bg-amber-950/80 text-amber-300 border-amber-500/30",
};

const DATA_SOURCE_COLORS: Record<DataSource, string> = {
  EMPLOYEE: "bg-indigo-950/60 text-indigo-300 border-indigo-500/20",
  COMPANY:  "bg-cyan-950/60 text-cyan-300 border-cyan-500/20",
  PROFILE:  "bg-violet-950/60 text-violet-300 border-violet-500/20",
  SYSTEM:   "bg-amber-950/60 text-amber-300 border-amber-500/20",
  MANUAL:   "bg-rose-950/60 text-rose-300 border-rose-500/20",
};

// ─── Component ────────────────────────────────────────────────────────────────

export default function DynamicFieldManagementPage() {
  const [collapsed, setCollapsed] = useState(false);

  // ── Data State ──────────────────────────────────────────────────────────────
  const [fields, setFields]               = useState<DynamicField[]>([]);
  const [documentTypes, setDocumentTypes] = useState<DocumentType[]>([]);
  const [loading, setLoading]             = useState<boolean>(true);
  const [error, setError]                 = useState<string | null>(null);

  // ── Filters ─────────────────────────────────────────────────────────────────
  const [searchTerm,      setSearchTerm]      = useState<string>("");
  const [fieldTypeFilter, setFieldTypeFilter] = useState<string>("all");
  const [dataSourceFilter,setDataSourceFilter]= useState<string>("all");
  const [docTypeFilter,   setDocTypeFilter]   = useState<string>("all");
  const [activeFilter,    setActiveFilter]    = useState<string>("all");
  const [selectedIds,     setSelectedIds]     = useState<number[]>([]);

  // ── Modal State ──────────────────────────────────────────────────────────────
  const [isFormModalOpen,  setIsFormModalOpen]  = useState<boolean>(false);
  const [isDeleteModalOpen,setIsDeleteModalOpen]= useState<boolean>(false);
  const [deletingField,    setDeletingField]    = useState<DynamicField | null>(null);
  const [editingField,     setEditingField]     = useState<DynamicField | null>(null);
  const [formSubmitting,   setFormSubmitting]   = useState<boolean>(false);
  const [deleteSubmitting, setDeleteSubmitting] = useState<boolean>(false);

  // ── Toast ───────────────────────────────────────────────────────────────────
  const [toast, setToast] = useState<{ type: "success" | "error"; msg: string } | null>(null);

  // ── Key UX ──────────────────────────────────────────────────────────────────
  // Track whether user has manually edited the field key (to not auto-overwrite)
  const fieldKeyManuallyEdited = useRef<boolean>(false);
  const [copiedKey, setCopiedKey] = useState<boolean>(false);

  const showToast = (type: "success" | "error", msg: string) => {
    setToast({ type, msg });
    setTimeout(() => setToast(null), 4500);
  };

  // ─── Default Form State ─────────────────────────────────────────────────────
  const blankForm = (): CreateDynamicFieldPayload => ({
    fieldKey:       "",
    fieldName:      "",
    fieldType:      "TEXT",
    dataSource:     "EMPLOYEE",
    documentTypeId: null,
    description:    "",
    placeholder:    "",
    defaultValue:   "",
    isRequired:     false,
    isActive:       true,
    isSystem:       false,
    displayOrder:   1,
  });

  const [formData, setFormData] = useState<CreateDynamicFieldPayload>(blankForm());

  // ── Search Debounce ─────────────────────────────────────────────────────────
  const debounceTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const [debouncedSearch, setDebouncedSearch] = useState<string>("");

  const handleSearchChange = (val: string) => {
    setSearchTerm(val);
    if (debounceTimer.current) clearTimeout(debounceTimer.current);
    debounceTimer.current = setTimeout(() => setDebouncedSearch(val), 350);
  };

  // ── Load Data ───────────────────────────────────────────────────────────────
  const fetchData = useCallback(async (filters?: DynamicFieldFilters) => {
    setLoading(true);
    setError(null);
    try {
      const [fieldData, docTypeData] = await Promise.all([
        dynamicFieldService.getDynamicFields(filters),
        documentTypeService.getAllDocumentTypes().catch(() => []),
      ]);
      setFields(fieldData);
      setDocumentTypes(docTypeData);
    } catch (err: any) {
      console.error("Fetch dynamic fields error:", err);
      setError(err?.message || "Failed to load dynamic fields.");
      showToast("error", err?.message || "Unable to fetch dynamic fields.");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  // Rebuild server-side filters when any filter changes
  useEffect(() => {
    const filters: DynamicFieldFilters = {};
    if (debouncedSearch) filters.search = debouncedSearch;
    if (fieldTypeFilter !== "all") filters.field_type = fieldTypeFilter as FieldType;
    if (dataSourceFilter !== "all") filters.data_source = dataSourceFilter as DataSource;
    if (docTypeFilter !== "all") filters.document_type_id = Number(docTypeFilter);
    if (activeFilter !== "all") filters.is_active = activeFilter === "active";
    fetchData(filters);
  }, [debouncedSearch, fieldTypeFilter, dataSourceFilter, docTypeFilter, activeFilter]);

  // ── Form Helpers ─────────────────────────────────────────────────────────────
  const handleFieldNameChange = (name: string) => {
    setFormData((prev) => {
      const update: Partial<CreateDynamicFieldPayload> = { fieldName: name };
      // Auto-suggest field key only when not manually edited AND in create mode
      if (!fieldKeyManuallyEdited.current && !editingField) {
        update.fieldKey = toFieldKey(name);
      }
      return { ...prev, ...update };
    });
  };

  const handleFieldKeyChange = (key: string) => {
    fieldKeyManuallyEdited.current = true;
    // Sanitize: only allow lowercase letters, digits and underscores
    const sanitized = key.toLowerCase().replace(/[^a-z0-9_]/g, "");
    setFormData((prev) => ({ ...prev, fieldKey: sanitized }));
  };

  const copyFieldKey = () => {
    if (!formData.fieldKey) return;
    navigator.clipboard.writeText(`{{${formData.fieldKey}}}`).catch(() => {});
    setCopiedKey(true);
    setTimeout(() => setCopiedKey(false), 1500);
  };

  // ── Open Modals ──────────────────────────────────────────────────────────────
  const handleOpenCreateModal = () => {
    setEditingField(null);
    fieldKeyManuallyEdited.current = false;
    setFormData(blankForm());
    setIsFormModalOpen(true);
  };

  const handleOpenEditModal = (f: DynamicField) => {
    setEditingField(f);
    fieldKeyManuallyEdited.current = true; // Lock key auto-suggest in edit mode
    setFormData({
      fieldKey:       f.fieldKey || "",
      fieldName:      f.fieldName || "",
      fieldType:      f.fieldType || "TEXT",
      dataSource:     f.dataSource || "EMPLOYEE",
      documentTypeId: f.documentTypeId ?? null,
      description:    f.description || "",
      placeholder:    f.placeholder || "",
      defaultValue:   f.defaultValue || "",
      isRequired:     Boolean(f.isRequired),
      isActive:       f.isActive !== false,
      isSystem:       Boolean(f.isSystem),
      displayOrder:   f.displayOrder || 1,
    });
    setIsFormModalOpen(true);
  };

  const handleOpenDeleteModal = (f: DynamicField) => {
    setDeletingField(f);
    setIsDeleteModalOpen(true);
  };

  // ── Submit Create / Update ───────────────────────────────────────────────────
  const handleSubmitForm = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.fieldKey || !formData.fieldName || !formData.fieldType || !formData.dataSource) {
      showToast("error", "Field Key, Field Name, Field Type and Data Source are required.");
      return;
    }
    setFormSubmitting(true);

    const payload: CreateDynamicFieldPayload = {
      ...formData,
      documentTypeId: formData.documentTypeId || null,
    };

    try {
      if (editingField) {
        const updated = await dynamicFieldService.updateDynamicField(editingField.id, payload);
        setFields((prev) => prev.map((f) => (f.id === editingField.id ? { ...f, ...updated } : f)));
        showToast("success", `Dynamic field "${payload.fieldName}" updated successfully!`);
      } else {
        const created = await dynamicFieldService.createDynamicField(payload);
        setFields((prev) => [created, ...prev]);
        showToast("success", `Dynamic field "${created.fieldName}" ({{${created.fieldKey}}}) created!`);
      }
      setIsFormModalOpen(false);
    } catch (err: any) {
      console.error("Save dynamic field error:", err);
      showToast("error", err?.message || "Failed to save dynamic field record.");
    } finally {
      setFormSubmitting(false);
    }
  };

  // ── Confirm Delete ───────────────────────────────────────────────────────────
  const handleConfirmDelete = async () => {
    if (!deletingField) return;
    setDeleteSubmitting(true);
    try {
      await dynamicFieldService.deleteDynamicField(deletingField.id, "Deleted via admin portal");
      setFields((prev) => prev.filter((f) => f.id !== deletingField.id));
      setSelectedIds((prev) => prev.filter((i) => i !== deletingField.id));
      showToast("success", `Dynamic field "${deletingField.fieldName}" deleted.`);
      setIsDeleteModalOpen(false);
      setDeletingField(null);
    } catch (err: any) {
      console.error("Delete dynamic field error:", err);
      showToast("error", err?.message || "Failed to delete dynamic field.");
    } finally {
      setDeleteSubmitting(false);
    }
  };

  // ── Bulk Delete ──────────────────────────────────────────────────────────────
  const handleBulkDelete = async () => {
    if (selectedIds.length === 0) return;
    if (!window.confirm(`Delete ${selectedIds.length} selected dynamic field(s)?`)) return;
    try {
      await dynamicFieldService.bulkDeleteDynamicFields(selectedIds, "Bulk deleted via admin portal");
      setFields((prev) => prev.filter((f) => !selectedIds.includes(f.id)));
      showToast("success", `${selectedIds.length} field(s) deleted.`);
      setSelectedIds([]);
    } catch (err: any) {
      showToast("error", err?.message || "Bulk delete failed.");
    }
  };

  // ── Checkbox helpers ─────────────────────────────────────────────────────────
  const toggleSelectAll  = () =>
    setSelectedIds(selectedIds.length === fields.length ? [] : fields.map((f) => f.id));
  const toggleSelectOne  = (id: number) =>
    setSelectedIds((prev) => prev.includes(id) ? prev.filter((i) => i !== id) : [...prev, id]);

  // ── Data Source helper ───────────────────────────────────────────────────────
  const getDataSourceMeta = (src: DataSource) =>
    DATA_SOURCES.find((d) => d.value === src) || DATA_SOURCES[0];

  const getFieldTypeMeta = (type: FieldType) =>
    FIELD_TYPES.find((t) => t.value === type) || FIELD_TYPES[0];

  // ─────────────────────────────────────────────────────────────────────────────

  return (
    <div className="min-h-screen bg-[#070911] text-slate-100 flex flex-col font-sans selection:bg-indigo-500 selection:text-white">
      <Sidebar collapsed={collapsed} setCollapsed={setCollapsed} />

      <main
        className={`flex-1 transition-all duration-300 ease-in-out p-4 sm:p-6 lg:p-8 ${
          collapsed ? "ml-20" : "ml-64"
        }`}
      >
        <div className="max-w-7xl mx-auto space-y-6">

          {/* Toast Notification */}
          {toast && (
            <div
              className={`p-4 rounded-xl text-xs font-semibold shadow-2xl flex items-center justify-between border animate-in slide-in-from-top duration-200 ${
                toast.type === "success"
                  ? "bg-emerald-950/90 text-emerald-200 border-emerald-500/40"
                  : "bg-rose-950/90 text-rose-200 border-rose-500/40"
              }`}
            >
              <div className="flex items-center gap-2">
                {toast.type === "success" ? (
                  <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                ) : (
                  <AlertCircle className="w-4 h-4 text-rose-400" />
                )}
                <span>{toast.msg}</span>
              </div>
              <button onClick={() => setToast(null)}>
                <X className="w-3.5 h-3.5 opacity-70 hover:opacity-100" />
              </button>
            </div>
          )}

          {/* Page Header */}
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div>
              <div className="flex items-center gap-3">
                <h1 className="text-3xl font-extrabold text-white tracking-tight">
                  Dynamic Fields
                </h1>
                <span className="text-[10px] font-mono px-2.5 py-0.5 rounded bg-indigo-950/80 text-indigo-300 border border-indigo-500/30 flex items-center gap-1">
                  <ShieldCheck className="w-3 h-3" /> Phase 4B
                </span>
              </div>
              <p className="text-xs text-slate-400 mt-1">
                Manage reusable fields used in corporate document templates.
              </p>
            </div>

            <div className="flex items-center gap-3">
              <button
                onClick={() => fetchData()}
                className="p-2.5 rounded-xl bg-[#0F1422] hover:bg-[#151C2F] text-slate-400 hover:text-white border border-[#1E2638] transition-all"
                title="Refresh"
              >
                <RefreshCw className={`w-4 h-4 ${loading ? "animate-spin" : ""}`} />
              </button>

              <button
                onClick={handleOpenCreateModal}
                className="gradient-btn flex items-center gap-2 px-5 py-2.5 rounded-xl text-white font-semibold text-xs cursor-pointer shadow-lg shadow-indigo-500/20"
              >
                <Plus className="w-4 h-4" />
                <span>Add Dynamic Field</span>
              </button>
            </div>
          </div>

          {/* Error Banner */}
          {error && (
            <div className="p-4 rounded-xl bg-rose-950/80 border border-rose-500/40 text-rose-300 text-xs font-medium flex items-center justify-between">
              <div className="flex items-center gap-2">
                <AlertCircle className="w-4 h-4 text-rose-400" />
                <span>{error}</span>
              </div>
              <button
                onClick={() => fetchData()}
                className="px-3 py-1 bg-rose-900 hover:bg-rose-800 rounded text-[11px] text-white font-semibold"
              >
                Retry
              </button>
            </div>
          )}

          {/* KPI Tiles */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
            <div className="glass-card p-4 rounded-xl border border-[#1E2638]">
              <span className="text-[11px] text-slate-400 block mb-1 font-medium">Total Fields</span>
              <span className="text-2xl font-extrabold text-white font-mono">{fields.length}</span>
            </div>
            <div className="glass-card p-4 rounded-xl border border-[#1E2638]">
              <span className="text-[11px] text-slate-400 block mb-1 font-medium">Active Fields</span>
              <span className="text-2xl font-extrabold text-emerald-400 font-mono">
                {fields.filter((f) => f.isActive !== false).length}
              </span>
            </div>
            <div className="glass-card p-4 rounded-xl border border-[#1E2638]">
              <span className="text-[11px] text-slate-400 block mb-1 font-medium">Required</span>
              <span className="text-2xl font-extrabold text-indigo-400 font-mono">
                {fields.filter((f) => f.isRequired).length}
              </span>
            </div>
            <div className="glass-card p-4 rounded-xl border border-[#1E2638]">
              <span className="text-[11px] text-slate-400 block mb-1 font-medium">Document Types</span>
              <span className="text-2xl font-extrabold text-cyan-400 font-mono">{documentTypes.length}</span>
            </div>
          </div>

          {/* Filters & Search Bar */}
          <div className="glass-card p-4 rounded-2xl border border-[#1E2638] space-y-3">
            <div className="flex flex-wrap items-center gap-3">
              {/* Search */}
              <div className="relative flex-1 min-w-[220px] max-w-sm">
                <Search className="w-4 h-4 text-slate-500 absolute left-3.5 top-2.5" />
                <input
                  type="text"
                  placeholder="Search field name, key, description..."
                  value={searchTerm}
                  onChange={(e) => handleSearchChange(e.target.value)}
                  className="w-full bg-[#141A2C] border border-[#202B44] rounded-xl pl-9 pr-4 py-2 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-indigo-500"
                />
              </div>

              <div className="flex items-center gap-2 text-slate-400">
                <Filter className="w-3.5 h-3.5" />
                <span className="text-[10px] font-mono uppercase tracking-wider">Filters</span>
              </div>

              {/* Field Type */}
              <select
                value={fieldTypeFilter}
                onChange={(e) => setFieldTypeFilter(e.target.value)}
                className="bg-[#141A2C] border border-[#202B44] rounded-xl px-3 py-2 text-xs text-slate-200 focus:outline-none focus:border-indigo-500 cursor-pointer"
              >
                <option value="all" className="bg-[#141A2C]">All Field Types</option>
                {FIELD_TYPES.map((ft) => (
                  <option key={ft.value} value={ft.value} className="bg-[#141A2C]">
                    {ft.value} — {ft.label}
                  </option>
                ))}
              </select>

              {/* Data Source */}
              <select
                value={dataSourceFilter}
                onChange={(e) => setDataSourceFilter(e.target.value)}
                className="bg-[#141A2C] border border-[#202B44] rounded-xl px-3 py-2 text-xs text-slate-200 focus:outline-none focus:border-indigo-500 cursor-pointer"
              >
                <option value="all" className="bg-[#141A2C]">All Data Sources</option>
                {DATA_SOURCES.map((ds) => (
                  <option key={ds.value} value={ds.value} className="bg-[#141A2C]">
                    {ds.value} — {ds.label}
                  </option>
                ))}
              </select>

              {/* Document Type */}
              <select
                value={docTypeFilter}
                onChange={(e) => setDocTypeFilter(e.target.value)}
                className="bg-[#141A2C] border border-[#202B44] rounded-xl px-3 py-2 text-xs text-slate-200 focus:outline-none focus:border-indigo-500 cursor-pointer"
              >
                <option value="all" className="bg-[#141A2C]">All Documents</option>
                {documentTypes.map((dt) => (
                  <option key={dt.id} value={dt.id} className="bg-[#141A2C]">
                    {dt.documentTypeName}
                  </option>
                ))}
              </select>

              {/* Status */}
              <select
                value={activeFilter}
                onChange={(e) => setActiveFilter(e.target.value)}
                className="bg-[#141A2C] border border-[#202B44] rounded-xl px-3 py-2 text-xs text-slate-200 focus:outline-none focus:border-indigo-500 cursor-pointer"
              >
                <option value="all"      className="bg-[#141A2C]">All Statuses</option>
                <option value="active"   className="bg-[#141A2C]">Active</option>
                <option value="inactive" className="bg-[#141A2C]">Inactive</option>
              </select>
            </div>

            {/* Bulk Actions */}
            {selectedIds.length > 0 && (
              <div className="flex items-center gap-3 pt-2 border-t border-[#1E2638] animate-in fade-in">
                <span className="text-xs text-indigo-400 font-mono">{selectedIds.length} selected</span>
                <button
                  onClick={handleBulkDelete}
                  className="px-3 py-1.5 rounded-lg bg-rose-950/80 hover:bg-rose-900 border border-rose-500/40 text-rose-300 text-xs font-semibold flex items-center gap-1.5 transition-all"
                >
                  <Trash2 className="w-3.5 h-3.5" />
                  <span>Delete Selected</span>
                </button>
                <button
                  onClick={() => setSelectedIds([])}
                  className="text-xs text-slate-500 hover:text-slate-300 transition-colors"
                >
                  Clear Selection
                </button>
              </div>
            )}
          </div>

          {/* Dynamic Fields Table */}
          <div className="glass-card rounded-2xl border border-[#1E2638] overflow-hidden">
            {loading ? (
              <div className="p-16 text-center text-slate-400 space-y-3">
                <RefreshCw className="w-8 h-8 animate-spin mx-auto text-indigo-500" />
                <p className="text-xs font-mono">Loading dynamic fields directory...</p>
              </div>
            ) : fields.length === 0 ? (
              /* ── Empty State ── */
              <div className="py-20 text-center space-y-5">
                <div className="w-16 h-16 rounded-2xl bg-indigo-600/10 border border-indigo-500/20 flex items-center justify-center mx-auto">
                  <FormInput className="w-8 h-8 text-indigo-400" />
                </div>
                <div className="space-y-2">
                  <h3 className="text-base font-bold text-white">No Dynamic Fields Yet</h3>
                  <p className="text-xs text-slate-400 max-w-xs mx-auto leading-relaxed">
                    Create reusable fields that can later be inserted into your document templates.
                  </p>
                </div>
                <button
                  onClick={handleOpenCreateModal}
                  className="gradient-btn inline-flex items-center gap-2 px-5 py-2.5 rounded-xl text-white font-semibold text-xs cursor-pointer shadow-lg shadow-indigo-500/20"
                >
                  <Plus className="w-4 h-4" />
                  Add Dynamic Field
                </button>
              </div>
            ) : (
              <div className="overflow-x-auto">
                <table className="w-full text-left text-xs text-slate-300">
                  <thead className="bg-[#0B0E1B] text-slate-400 font-mono uppercase text-[10px] tracking-wider border-b border-[#1E2638]">
                    <tr>
                      <th className="py-3.5 px-4 w-10">
                        <button onClick={toggleSelectAll} className="text-slate-400 hover:text-white">
                          {selectedIds.length === fields.length && fields.length > 0 ? (
                            <CheckSquare className="w-4 h-4 text-indigo-400" />
                          ) : (
                            <Square className="w-4 h-4" />
                          )}
                        </button>
                      </th>
                      <th className="py-3.5 px-4 font-bold">Field Name</th>
                      <th className="py-3.5 px-4 font-bold">Field Key</th>
                      <th className="py-3.5 px-4 font-bold">Field Type</th>
                      <th className="py-3.5 px-4 font-bold">Data Source</th>
                      <th className="py-3.5 px-4 font-bold">Document Type</th>
                      <th className="py-3.5 px-4 font-bold">Required</th>
                      <th className="py-3.5 px-4 font-bold">Status</th>
                      <th className="py-3.5 px-4 font-bold text-right">Actions</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-[#1E2638]">
                    {fields.map((f) => {
                      const isSelected   = selectedIds.includes(f.id);
                      const docTypeObj   = documentTypes.find((d) => d.id === f.documentTypeId);
                      const ftMeta       = getFieldTypeMeta(f.fieldType);
                      const dsMeta       = getDataSourceMeta(f.dataSource);

                      return (
                        <tr
                          key={f.id}
                          className={`hover:bg-[#121829] transition-colors group ${
                            isSelected ? "bg-indigo-950/20" : ""
                          }`}
                        >
                          <td className="py-3.5 px-4" onClick={(e) => e.stopPropagation()}>
                            <button onClick={() => toggleSelectOne(f.id)} className="text-slate-400 hover:text-white">
                              {isSelected ? (
                                <CheckSquare className="w-4 h-4 text-indigo-400" />
                              ) : (
                                <Square className="w-4 h-4" />
                              )}
                            </button>
                          </td>

                          {/* Field Name */}
                          <td className="py-3.5 px-4">
                            <span className="font-bold text-white block group-hover:text-indigo-300 transition-colors">
                              {f.fieldName}
                            </span>
                            {f.description && (
                              <span className="text-[10px] text-slate-500 truncate block max-w-[180px]">
                                {f.description}
                              </span>
                            )}
                          </td>

                          {/* Field Key */}
                          <td className="py-3.5 px-4">
                            <span className="font-mono text-[11px] text-indigo-300 bg-indigo-950/40 border border-indigo-500/20 px-2 py-0.5 rounded">
                              {`{{${f.fieldKey}}}`}
                            </span>
                          </td>

                          {/* Field Type */}
                          <td className="py-3.5 px-4">
                            <span
                              className={`inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[10px] font-semibold font-mono border ${
                                FIELD_TYPE_COLORS[f.fieldType] || "bg-slate-900 text-slate-400 border-slate-700"
                              }`}
                            >
                              {f.fieldType}
                            </span>
                          </td>

                          {/* Data Source */}
                          <td className="py-3.5 px-4">
                            <span
                              className={`inline-flex items-center gap-1.5 px-2 py-0.5 rounded text-[10px] font-semibold border ${
                                DATA_SOURCE_COLORS[f.dataSource] || "bg-slate-900 text-slate-400 border-slate-700"
                              }`}
                            >
                              <Database className="w-2.5 h-2.5" />
                              {f.dataSource}
                            </span>
                          </td>

                          {/* Document Type */}
                          <td className="py-3.5 px-4 text-slate-300 font-medium">
                            {docTypeObj ? (
                              <span className="flex items-center gap-1">
                                <FileText className="w-3 h-3 text-slate-500" />
                                {docTypeObj.documentTypeName}
                              </span>
                            ) : (
                              <span className="text-slate-500 italic text-[10px]">All Documents</span>
                            )}
                          </td>

                          {/* Required */}
                          <td className="py-3.5 px-4">
                            {f.isRequired ? (
                              <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-emerald-950 text-emerald-400 border border-emerald-500/30">
                                Yes
                              </span>
                            ) : (
                              <span className="px-2 py-0.5 rounded text-[10px] text-slate-500 bg-slate-900 border border-slate-800">
                                No
                              </span>
                            )}
                          </td>

                          {/* Status */}
                          <td className="py-3.5 px-4">
                            {f.isActive !== false ? (
                              <span className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-xs font-semibold bg-emerald-950/80 text-emerald-400 border border-emerald-500/30">
                                <CheckCircle2 className="w-3 h-3" /> Active
                              </span>
                            ) : (
                              <span className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-xs font-semibold bg-slate-900 text-slate-400 border border-slate-700">
                                Inactive
                              </span>
                            )}
                          </td>

                          {/* Actions */}
                          <td className="py-3.5 px-4 text-right" onClick={(e) => e.stopPropagation()}>
                            <div className="flex items-center justify-end gap-1.5">
                              <button
                                onClick={() => handleOpenEditModal(f)}
                                className="p-1.5 rounded-lg bg-[#141A2C] hover:bg-[#1C253E] text-slate-400 hover:text-cyan-400 transition-colors"
                                title="Edit Field"
                              >
                                <Edit2 className="w-3.5 h-3.5" />
                              </button>
                              <button
                                onClick={() => handleOpenDeleteModal(f)}
                                className="p-1.5 rounded-lg bg-[#141A2C] hover:bg-[#1C253E] text-slate-400 hover:text-rose-400 transition-colors"
                                title="Delete Field"
                              >
                                <Trash2 className="w-3.5 h-3.5" />
                              </button>
                            </div>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>

                <div className="px-4 py-3 border-t border-[#1E2638] flex items-center justify-between text-[10px] text-slate-500 font-mono">
                  <span>{fields.length} field(s) displayed</span>
                  <span>Phase 4B • Dynamic Field Master</span>
                </div>
              </div>
            )}
          </div>
        </div>
      </main>

      {/* ═══════════════════════════════════════════════════════════════════════
          CREATE / EDIT DYNAMIC FIELD MODAL
      ═══════════════════════════════════════════════════════════════════════ */}
      {isFormModalOpen && (
        <div className="fixed inset-0 z-50 flex items-start justify-center pt-12 px-4 pb-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-150 overflow-y-auto">
          <div className="bg-[#0F1424] border border-[#1E273E] w-full max-w-2xl rounded-2xl shadow-2xl overflow-hidden relative">
            {/* Modal Header */}
            <div className="flex items-center justify-between p-5 border-b border-[#1E2638] bg-[#0C101D]">
              <div className="flex items-center gap-3">
                <div className="w-9 h-9 rounded-xl bg-indigo-600/20 text-indigo-400 border border-indigo-500/30 flex items-center justify-center">
                  <FormInput className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="text-base font-bold text-white">
                    {editingField ? `Edit Field — ${editingField.fieldKey}` : "Create Dynamic Field"}
                  </h3>
                  <p className="text-xs text-slate-400">
                    {editingField
                      ? "Update field properties — the key will be preserved unless explicitly changed."
                      : "Define a reusable placeholder field for corporate document templates."}
                  </p>
                </div>
              </div>
              <button
                onClick={() => setIsFormModalOpen(false)}
                className="p-1.5 rounded-lg bg-[#141A2B] text-slate-400 hover:text-white transition-colors"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            {/* Form Body */}
            <form onSubmit={handleSubmitForm} className="p-6 space-y-5 overflow-y-auto max-h-[75vh]">

              {/* Field Name & Field Key (linked) */}
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-semibold text-slate-300 mb-1">
                    Field Name <span className="text-rose-400">*</span>
                  </label>
                  <input
                    type="text"
                    required
                    placeholder="e.g. Employee Name"
                    value={formData.fieldName}
                    onChange={(e) => handleFieldNameChange(e.target.value)}
                    className="w-full bg-[#141A2C] border border-[#202B44] rounded-xl px-4 py-2 text-xs text-white focus:outline-none focus:border-indigo-500"
                  />
                </div>

                <div>
                  <label className="block text-xs font-semibold text-slate-300 mb-1">
                    Field Key <span className="text-rose-400">*</span>
                    <span className="text-[10px] text-slate-500 font-normal ml-1">(snake_case)</span>
                  </label>
                  <div className="relative">
                    <input
                      type="text"
                      required
                      placeholder="e.g. employee_name"
                      value={formData.fieldKey}
                      onChange={(e) => handleFieldKeyChange(e.target.value)}
                      className="w-full bg-[#141A2C] border border-[#202B44] rounded-xl px-4 py-2 pr-9 text-xs text-white font-mono focus:outline-none focus:border-indigo-500"
                    />
                    {formData.fieldKey && (
                      <button
                        type="button"
                        onClick={copyFieldKey}
                        className="absolute right-2 top-1.5 p-1 text-slate-500 hover:text-indigo-400 transition-colors"
                        title="Copy template placeholder"
                      >
                        {copiedKey ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                      </button>
                    )}
                  </div>
                  {formData.fieldKey && (
                    <div className="mt-1 flex items-center gap-1.5">
                      <Sparkles className="w-3 h-3 text-indigo-400" />
                      <span className="text-[10px] text-slate-400">
                        Template placeholder:{" "}
                        <code className="text-indigo-300 font-mono">{`{{${formData.fieldKey}}}`}</code>
                        <span className="text-slate-500 ml-1">— used inside document templates</span>
                      </span>
                    </div>
                  )}
                </div>
              </div>

              {/* Field Type */}
              <div>
                <label className="block text-xs font-semibold text-slate-300 mb-2">
                  Field Type <span className="text-rose-400">*</span>
                </label>
                <div className="grid grid-cols-4 sm:grid-cols-7 gap-2">
                  {FIELD_TYPES.map((ft) => {
                    const Icon = ft.icon;
                    const isSelected = formData.fieldType === ft.value;
                    return (
                      <button
                        key={ft.value}
                        type="button"
                        onClick={() => setFormData((prev) => ({ ...prev, fieldType: ft.value }))}
                        className={`flex flex-col items-center gap-1.5 px-2 py-3 rounded-xl border text-[10px] font-semibold transition-all ${
                          isSelected
                            ? "bg-indigo-600/20 border-indigo-500/60 text-indigo-300"
                            : "bg-[#141A2C] border-[#202B44] text-slate-400 hover:border-indigo-500/40 hover:text-slate-200"
                        }`}
                      >
                        <Icon className="w-4 h-4" />
                        <span>{ft.value}</span>
                      </button>
                    );
                  })}
                </div>
                {/* Field Type Helper */}
                <div className="mt-2 p-2.5 rounded-lg bg-[#0C1020] border border-[#1E2638] text-[11px] text-slate-400">
                  <span className="text-indigo-300 font-semibold">{formData.fieldType}:</span>{" "}
                  {getFieldTypeMeta(formData.fieldType)?.description}
                </div>
              </div>

              {/* Data Source */}
              <div>
                <label className="block text-xs font-semibold text-slate-300 mb-2">
                  Data Source <span className="text-rose-400">*</span>
                </label>
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
                  {DATA_SOURCES.map((ds) => {
                    const isSelected = formData.dataSource === ds.value;
                    return (
                      <button
                        key={ds.value}
                        type="button"
                        onClick={() => setFormData((prev) => ({ ...prev, dataSource: ds.value }))}
                        className={`text-left px-3 py-2.5 rounded-xl border transition-all ${
                          isSelected
                            ? "bg-indigo-600/20 border-indigo-500/60"
                            : "bg-[#141A2C] border-[#202B44] hover:border-indigo-500/40"
                        }`}
                      >
                        <span className={`text-xs font-bold block ${isSelected ? "text-white" : "text-slate-300"}`}>
                          {ds.value}
                        </span>
                        <span className="text-[10px] text-slate-500 leading-tight block mt-0.5">{ds.description}</span>
                      </button>
                    );
                  })}
                </div>
              </div>

              {/* Document Type (optional) */}
              <div>
                <label className="block text-xs font-semibold text-slate-300 mb-1">
                  Document Type
                  <span className="text-[10px] text-slate-500 font-normal ml-1">
                    (Optional — leave blank to apply across all document types)
                  </span>
                </label>
                <select
                  value={formData.documentTypeId ?? ""}
                  onChange={(e) =>
                    setFormData((prev) => ({
                      ...prev,
                      documentTypeId: e.target.value ? Number(e.target.value) : null,
                    }))
                  }
                  className="w-full bg-[#141A2C] border border-[#202B44] rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-indigo-500"
                >
                  <option value="" className="bg-[#141A2C]">All Documents (Global Field)</option>
                  {documentTypes.map((dt) => (
                    <option key={dt.id} value={dt.id} className="bg-[#141A2C]">
                      {dt.documentTypeName} ({dt.documentTypeCode})
                    </option>
                  ))}
                </select>
              </div>

              {/* Description */}
              <div>
                <label className="block text-xs font-semibold text-slate-300 mb-1">Description</label>
                <input
                  type="text"
                  placeholder="Brief explanation of this field's purpose..."
                  value={formData.description || ""}
                  onChange={(e) => setFormData((prev) => ({ ...prev, description: e.target.value }))}
                  className="w-full bg-[#141A2C] border border-[#202B44] rounded-xl px-4 py-2 text-xs text-white focus:outline-none focus:border-indigo-500"
                />
              </div>

              {/* Default Value + Placeholder */}
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-semibold text-slate-300 mb-1">Default Value</label>
                  <input
                    type="text"
                    placeholder="Optional default..."
                    value={formData.defaultValue || ""}
                    onChange={(e) => setFormData((prev) => ({ ...prev, defaultValue: e.target.value }))}
                    className="w-full bg-[#141A2C] border border-[#202B44] rounded-xl px-4 py-2 text-xs text-white focus:outline-none focus:border-indigo-500"
                  />
                </div>
                <div>
                  <label className="block text-xs font-semibold text-slate-300 mb-1">Placeholder Text</label>
                  <input
                    type="text"
                    placeholder="e.g. Enter employee name"
                    value={formData.placeholder || ""}
                    onChange={(e) => setFormData((prev) => ({ ...prev, placeholder: e.target.value }))}
                    className="w-full bg-[#141A2C] border border-[#202B44] rounded-xl px-4 py-2 text-xs text-white focus:outline-none focus:border-indigo-500"
                  />
                </div>
              </div>

              {/* Toggles */}
              <div className="flex flex-wrap items-center gap-6 p-4 bg-[#0C1020] rounded-xl border border-[#1E2638]">
                <label className="flex items-center gap-2 text-xs text-slate-300 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={Boolean(formData.isRequired)}
                    onChange={(e) => setFormData((prev) => ({ ...prev, isRequired: e.target.checked }))}
                    className="rounded bg-[#141A2C] border-[#202B44] text-indigo-600 focus:ring-0 cursor-pointer"
                  />
                  <span className="font-semibold">Required Field</span>
                  <span className="text-slate-500">— mandatory in document generation</span>
                </label>

                <label className="flex items-center gap-2 text-xs text-slate-300 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={formData.isActive !== false}
                    onChange={(e) => setFormData((prev) => ({ ...prev, isActive: e.target.checked }))}
                    className="rounded bg-[#141A2C] border-[#202B44] text-indigo-600 focus:ring-0 cursor-pointer"
                  />
                  <span className="font-semibold">Active</span>
                  <span className="text-slate-500">— visible and usable in templates</span>
                </label>

                <label className="flex items-center gap-2 text-xs text-slate-300 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={Boolean(formData.isSystem)}
                    onChange={(e) => setFormData((prev) => ({ ...prev, isSystem: e.target.checked }))}
                    className="rounded bg-[#141A2C] border-[#202B44] text-indigo-600 focus:ring-0 cursor-pointer"
                  />
                  <span className="font-semibold">System Reserved</span>
                  <span className="text-slate-500">— auto-populated by system</span>
                </label>
              </div>

              {/* Modal Footer */}
              <div className="pt-2 flex items-center justify-between border-t border-[#1E2638]">
                <p className="text-[10px] text-slate-500 font-mono">
                  {editingField ? "Preserve field_key unless explicitly changed." : "Field key uniqueness is validated by the backend."}
                </p>
                <div className="flex items-center gap-3">
                  <button
                    type="button"
                    onClick={() => setIsFormModalOpen(false)}
                    className="px-4 py-2 rounded-xl text-xs font-semibold text-slate-400 hover:text-white transition-colors"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    disabled={formSubmitting}
                    className="gradient-btn px-6 py-2 rounded-xl text-xs font-semibold text-white cursor-pointer shadow-md shadow-indigo-500/20 disabled:opacity-40"
                  >
                    {formSubmitting ? "Saving..." : editingField ? "Save Changes" : "Create Dynamic Field"}
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* ═══════════════════════════════════════════════════════════════════════
          DELETE CONFIRMATION MODAL
      ═══════════════════════════════════════════════════════════════════════ */}
      {isDeleteModalOpen && deletingField && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-150">
          <div className="bg-[#0F1424] border border-rose-500/30 w-full max-w-md rounded-2xl shadow-2xl p-6 space-y-4">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-rose-600/20 text-rose-400 border border-rose-500/30 flex items-center justify-center">
                <Trash2 className="w-5 h-5" />
              </div>
              <div>
                <h3 className="text-sm font-bold text-white">Delete Dynamic Field</h3>
                <p className="text-xs text-slate-400">This action cannot be undone.</p>
              </div>
            </div>

            <div className="p-4 bg-[#141A2C] rounded-xl border border-[#202B44] space-y-1.5">
              <div className="flex justify-between text-xs">
                <span className="text-slate-400">Field Name</span>
                <span className="text-white font-semibold">{deletingField.fieldName}</span>
              </div>
              <div className="flex justify-between text-xs">
                <span className="text-slate-400">Field Key</span>
                <code className="text-indigo-300 font-mono">{`{{${deletingField.fieldKey}}}`}</code>
              </div>
              <div className="flex justify-between text-xs">
                <span className="text-slate-400">Field Type</span>
                <span className="text-slate-200">{deletingField.fieldType}</span>
              </div>
              <div className="flex justify-between text-xs">
                <span className="text-slate-400">Data Source</span>
                <span className="text-slate-200">{deletingField.dataSource}</span>
              </div>
            </div>

            <p className="text-xs text-slate-400 leading-relaxed">
              This field will be <strong className="text-rose-300">soft-deleted</strong> from the system.
              It will no longer appear in the Dynamic Fields directory or be available for new template assignments.
            </p>

            <div className="flex items-center justify-end gap-3 pt-2 border-t border-[#1E2638]">
              <button
                type="button"
                onClick={() => { setIsDeleteModalOpen(false); setDeletingField(null); }}
                className="px-4 py-2 rounded-xl text-xs font-semibold text-slate-400 hover:text-white transition-colors"
              >
                Cancel
              </button>
              <button
                onClick={handleConfirmDelete}
                disabled={deleteSubmitting}
                className="px-5 py-2 rounded-xl text-xs font-bold text-white bg-rose-700 hover:bg-rose-600 transition-colors flex items-center gap-2 disabled:opacity-40"
              >
                <Trash2 className="w-3.5 h-3.5" />
                {deleteSubmitting ? "Deleting..." : "Delete Field"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
